"""
Constants module for DataRoom Intelligence Bot
"""

from .analyst_schema import (
    SECTIONS_ORDER,
    SECTION_TITLE,
    FIELDS,
    FIELD_ALIASES,
    CRITICAL_SECTIONS,
    NICE_TO_HAVE_SECTIONS,
    BULLETS_LIMITS,
    DEFAULT_BULLET_LIMIT,
    MAX_TOTAL_BULLETS
)

__all__ = [
    'SECTIONS_ORDER',
    'SECTION_TITLE',
    'FIELDS',
    'FIELD_ALIASES',
    'CRITICAL_SECTIONS',
    'NICE_TO_HAVE_SECTIONS',
    'BULLETS_LIMITS',
    'DEFAULT_BULLET_LIMIT',
    'MAX_TOTAL_BULLETS'
]